# url
url: "raceup.it"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog/

# site
title: Race UP Team
email: info@raceup.it
description: Race UP is the FSAE team of the University of Padova. Since 2006 we build one of the fastest racing car in FSAE competitions.
keywords: "raceup unipd fsae"

# allow posts with date in the future
future: true
permalink: /:year/:month/:day/:title

# plugins
gems: 
  - jekyll-multiple-languages-plugin
  # - jekyll-gallery-generator

# jekyll-multiple-languages-plugin settings:
languages: ["it", "en"]

# to avoid redundancy, it is possible to exclude files and folders from being copied to the localization folders.
exclude_from_localizations: ["javascript", "images", "css"]

# exclude from webpage
exclude: ["run_site.sh", "upload_site.sh", "imgopt.sh"]

# build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# guide here: https://desiredpersona.com/google-analytics-jekyll/
# google_analytics:

# gallery settings
# gallery:
#   dir: photos               # Path to the gallery
#   symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
#   title: "gallery-title"           # Title for gallery index page
#   title_prefix: "gallery-prefix"  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
#   sort_field: "date_time"   # How to sort galleries on the index page.
#                             # Possible values are: title, date_time, best_image
#   thumbnail_size:
#     x: 400                  # max width of thumbnails (in pixels)
#     y: 400                  # max height of thumbnails (in pixels)
#   
#   # The following options are for individual galleries.
#   galleries:
#     fsc2015:
#       name: "2015 - FSC"
#     misc2016:
#       name: "2016 - misc"
#     launch2017:
#       best_image: CRW_0173.jpg  # The image to show on the gallery index page. Defaults to the last image.
#       name: "2017 - car launch"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
#     with_info:
#       info:
#         desc: "Gallery Description" # Info fields can be used in custom templates.
# 