# site settings
title: RaceUp Team
email: info@raceup.it
description: RaceUp is the FSAE team of the University of Padova. Since 2006 we build one of the fastest racing car in FSAE competitions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "raceup.github.io" # the base hostname & protocol for your site

# social
twitter_username: RaceUpTeam
github_username: raceup

# plugins
gems: 
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["it", "en"]

# to avoid redundancy, it is possible to exclude files and folders from being copied to the localization folders.
exclude_from_localizations: ["javascript", "images", "css"]

# build settings
markdown: kramdown
