# url
url: "raceup.it"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog/

# site
title: Race UP Team
email: info@raceup.it
description: Race UP is the FSAE team of the University of Padova. Since 2006 we build one of the fastest racing car in FSAE competitions.
keywords: "raceup unipd fsae"

# allow posts with date in the future
future: true
permalink: /:year/:month/:day/:title

# plugins
gems: 
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["it", "en"]

# to avoid redundancy, it is possible to exclude files and folders from being copied to the localization folders.
exclude_from_localizations: ["javascript", "images", "css"]

# exclude from webpage
exclude: ["tmp/", "CHANGELOG.md", "README.md", "run_site.sh", "upload_site.sh", "must_exist_on_all_websites_roots.txt"]

# build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
